### ISSUE TITLE
Entering the name of a non-numeric column raises "min() arg is an empty sequence"

### ISSUE THREAD

**Issue by jeffreyliu** [sbebo/joypy#1]
If you enter the name of a column which corresponds to non-numeric data, the error message given is:
```
~/miniconda3/lib/python3.6/site-packages/joypy/joyplot.py in _joyplot(data, grid, labels, sublabels, xlabels, xlabelsize, xrot, ylabelsize, yrot, ax, figsize, hist, bins, fade, xlim, ylim, fill, linecolor, overlap, background, range_style, x_range, tails, title, legend, loc, colormap, color, **kwargs)
    352     else:
    353         global_x_range = _x_range(x_range, 0.0)
--> 354     global_x_min, global_x_max = min(global_x_range), max(global_x_range)
    355 
    356     # Each plot will have its own axis

ValueError: min() arg is an empty sequence
```

This was encountered when trying to make plots of datetime values. The error message is not informative that the error is due to datetime not being a numeric type. Perhaps in `_grouped_df_to_standard`, when you check if the column is numeric, you can throw a warning or error if there are no numeric columns returned.

**Comment by leotac** [comment]
Ah! I actually haven't tested it, but I assume scipy's `gaussian_kde` can't handle datetime values, so I'm only keeping numeric columns. 
But you're right, error handling is pretty much non-existent. I'll try to give a more meaningful message when no numeric column is selected.

**Comment by jeffreyliu** [comment]
I don't think it's b/c of `gaussian_kde` b/c it also fails when `hist=True` or `kind=counts`. I think the issue is that `_grouped_df_to_standard(grouped, column)` returns even if `converted` is empty.

Thanks btw for writing this! it's already been super helpful

**Comment by leotac** [comment]
Yes I got the issue, I know it's not a matter of `gaussian_kde` -- it never reaches that point. 
I was just thinking out loud. ;)
