### ISSUE TITLE
Verbose warning on import regarding `matplotlib.use()` call.

### ISSUE THREAD

**Issue by macks22** [sbebo/joypy#11]
I get the following warning when importing after importing `matplotlib.pyplot`. Seems to be caused by the call to mpl.use('Agg') in imports section of `joyplot.py`. This doesn't inhibit any functionality, but it is a huge eye-sore. I'm not sure what the motivation was for that call and I noticed an environment variable being checked before calling. I get this warning in an IPython notebook. Perhaps there is an additional check to perform there to prevent this?

> joyplot.py:9: UserWarning: 
> This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.
> ...

**Comment by leotac** [comment]
Should be fixed now.
