### ISSUE TITLE
One more example!

### ISSUE THREAD

**Issue by capitanevs** [sbebo/joypy#16]
Just a comment:

how about inserting in the HowTo section an example which does not involve the use of data frames?
Let's say I have such data

x = np.arange(0,100)

x= np.arange(0,100,0.1)
y =[]
for i in range(1,5):
	y.append(x**2)

how shall I use Joyplot with x and y?

Thanks!

**Comment by leotac** [comment]
I've added an example in the notebook and also fixed a bug that probably prevented you to use it with your data.
