### ISSUE TITLE
Provide aggregated data instead of detail?

### ISSUE THREAD

**Issue by Krp42** [sbebo/joypy#17]
Hi,

Is it possible to provide aggregated data to joyplot function ?

When working on big volume of data, we can not manipulate the unitary data in Python, so I would like to retrieve myself the number of occurrence (using database SQL aggregation) and send to joyplot the resulting aggregated table.

Could you please tell me how I can achieve that ?

Thank you.

Remi

**Comment by leotac** [comment]
Yes it's possible, there's an option to do that. 
Say you have a dataframe with columns ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] and rows with aggregated counts for each hour of the day.
Then you can plot using the argument `kind="values"`. 
Be aware that with that option you currently need to manually handle some stuff about the x axis (xticks and xrange), as follows:

```
import pandas as pd
import numpy as np
import joypy

#Generate random data
df = pd.DataFrame(np.random.poisson(10,(24,7)))
df.columns = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
```

||Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday|
|--|--|--|--|--|--|--|--|
|0|12|8|8|3|9|6|8|
|1|8|5|15|7|9|11|6|
|2|15|11|15|3|6|9|9|
|3|8|7|13|9|13|7|10|
|4|12|14|6|4|11|11|12|
|...|

```
#Plot
x_range = list(range(24))
fig, axes = joypy.joyplot(df, kind="values", x_range=x_range)
axes[-1].set_xticks(x_range)
axes[-1].set_xticklabels(x_range)
fig
```
![figure_1-1](https://user-images.githubusercontent.com/1311290/38130241-87327a7e-3402-11e8-823a-024a3d9b1ad8.png)


Note that, with the "values" option, if you want a smooth plot, you need to smooth the data yourself.

**Comment by Krp42** [comment]
Thank you very much for your quick answer. I'll give it a try.




Rémi




Télécharger Outlook pour Android







On Fri, Mar 30, 2018 at 5:16 PM +0900, "Leonardo Taccari" <notifications@github.com> wrote:












Yes it's possible, there's an option to do that.

Say you have a dataframe with columns ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] and rows with aggregated counts for each hour of the day.

Then you can plot using the argument kind="values".

Be aware that with that option you currently need to manually handle some stuff about the x axis (xticks and xrange), as follows:
import pandas as pd
import numpy as np
import joypy

#Generate random data
df = pd.DataFrame(np.random.poisson(10,(24,7)))
df.columns = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]





Monday
Tuesday
Wednesday
Thursday
Friday
Saturday
Sunday




0
12
8
8
3
9
6
8


1
8
5
15
7
9
11
6


2
15
11
15
3
6
9
9


3
8
7
13
9
13
7
10


4
12
14
6
4
11
11
12


...








#Plot
x_range = list(range(24))
fig, axes = joypy.joyplot(df, kind="values", x_range=x_range)
axes[-1].set_xticks(x_range)
axes[-1].set_xticklabels(x_range)
fig






Note that, with the "values" option, if you want a smooth plot, you need to smooth the data yourself.
