### ISSUE TITLE
Annotation, marker, text, etc on each density plot

### ISSUE THREAD

**Issue by Sungwon11** [sbebo/joypy#23]
Could there be a way we can annotate on or add some markers/text to each density (e.g., marking a certain point on the X axis of each and every density plot; put a little text on each, etc)?

**Comment by leotac** [comment]
Hi,

yes. The way to do it (manually) is to get the axes returned by `joypy.joyplot()` and work on them. Keep in mind the last one is the "global" one, while the other ones correspond to each subplot.

Example:

```python
import joypy
from matplotlib import pyplot as plt

iris = pd.read_csv("data/iris.csv")

# If you plot n subplots, joyplot returns n+1 axes
fig, axes = joypy.joyplot(iris)

# Use the first n axis to modify the subplots individually
axes[0].annotate("Plateau", (5.5, 0.5))
axes[1].annotate("Top", (3, 1.05), color="r")
axes[2].annotate("Valley", (2.5, 0.2), color="g")
axes[3].annotate("Flatland", (5, 0.1), color="b")

# Use the last axis if you want to add something globally
axes[-1].annotate("Global annotation", (8,0.6), rotation=-90, fontsize=15, color="orange")

plt.show()
```

![image](https://user-images.githubusercontent.com/1311290/46633229-5abc2480-cb4d-11e8-8c2e-baf57d39f7e5.png)
