### ISSUE TITLE
Titles in X and Y axis

### ISSUE THREAD

**Issue by dirmeier** [sbebo/joypy#25]
Hi, I have a question about Y labels and believe this functionality exists, but I cannot get it right. E.g.: I can put Y axis labels on every subplot something like this:
```python
fig, axes = joyploy(...)
for ax in axes:
    ax.set_ylabel("mylab")
```
This creates a label for **every** density plot. Can I somehow add a "global" Y axis label, instead of a Y axis label for every subplot. I suppose I can do that by providing an `ax` argument to `joyploy`, but it does not seem to work.

Thanks for your help,
Simon

**Comment by leotac** [comment]
There's no easy way - but to work on the "global" axis, you should consider the *last* of the axes returned by joyplot(), i.e., `axes[-1]`, whose y axis is not visible by default.
Then you can work on it as you with, after you made it visible again. But you need to manually take care of hiding the ticks, maybe moving the title on the right, and so on.

Quick (and ugly) example:

```python
%matplotlib inline
import joypy
import pandas as pd
from matplotlib import pyplot as plt

iris = pd.read_csv("data/iris.csv")
fig, axes = joypy.joyplot(iris)
ax = axes[-1]
ax.yaxis.set_label_position("right")
ax.set_ylabel("TestLabel")
ax.yaxis.set_visible(True)
ax.yaxis.set_ticks([])
```

![image](https://user-images.githubusercontent.com/1311290/46110580-5e15ee80-c1e4-11e8-9c78-2f4b68999e7a.png)

**Comment by dirmeier** [comment]
Awesome! That's a great idea, thanks!

**Comment by leotac** [comment]
You're welcome. 
To be clear -- the "axes" returned by joyplot, for a plot with **4** density plots like the one in the example above, is a list of **5** axes: the first four are the axis of the small plots, the last axis is the "global" one. I should add comments/docs that specify this better.
