### ISSUE TITLE
Get error when importing package

### ISSUE THREAD

**Issue by kieran-mace** [sbebo/joypy#3]
![screenshot from 2017-08-09 12-53-46](https://user-images.githubusercontent.com/18296227/29141323-a02ae0f0-7d02-11e7-92b4-bb4be8b61884.png)

seems like you're calling pandas.plotting incorrectly?

**Comment by leotac** [comment]
Hm, you're probably using pandas 0.19.x and pandas.plotting only appears in pandas from 0.20.x. So you need to update it.
I'll add the version to the requirements for the moment, and eventually I'll try to remove the dependency to those pandas internals if I can.

**Comment by kieran-mace** [comment]
works for me with pandas 0.20 thanks!
