### ISSUE TITLE
Getting y values of each subplot

### ISSUE THREAD

**Issue by IreneCrisologo** [sbebo/joypy#30]
Is there a way to get the y values of each subplot? I would like to plot several vertical lines corresponding to different quantities (for example, mean) and would like the line to go from the bottom of the plot up to the "top edge" of the plot (i.e. the y value).

For example, in the plot below I wanted to plot the mean but the vertical overshoots to plot (because I plotted until y=1)

![image](https://user-images.githubusercontent.com/4422950/52217437-b5b21e00-2898-11e9-8309-56e02f2e74e4.png)

**Comment by leotac** [comment]
You mean you want access to the y values of the curve? 
Exposing the data computed by kde would be a bit of a mess.

There is a workaround, as there always is in matplotlib.. -- you can extract the "line" elements for each axis and then extract the y values, then you can take the max. 

Something like:

```python
iris = pd.read_csv("iris.csv")
fig, axes = joypy.joyplot(iris)
median = [6,3,3.5,1]
for i in range(4): #the axis from 0 to 3 contain the actual subplots
    ymin = 0
    ymax = axes[i].lines[1].get_ydata().max() #the line we're interested in is actually the second one
    axes[i].plot([median[i]] * 2, [ymin, ymax], color="red", zorder=200) #need to set a high zorder to draw them in front of all the rest
```
resulting in:

![joy](https://user-images.githubusercontent.com/1311290/52469640-48e69e80-2b8c-11e9-9356-0aee569afa09.png)

**Comment by IreneCrisologo** [comment]
This is great, thank you! I had been exploring the axes elements and their sub-elements but somehow missed the get_ydata(). But thank you again!! 

Edit: Ah but wait.. Can I also get the y value at any x value from get_ydata()?

Edit 2: YES! So I wanted to get the mean value for each distribution and plot it. 

```
means = [iris.SepalLength.mean(), iris.SepalWidth.mean(), iris.PetalLength.mean(), iris.PetalWidth.mean()]

fig, axes = joypy.joyplot(iris)
for i in range(4): #the axis from 0 to 3 contain the actual subplots
    ymin = 0
    mean = means[i]
    yval = axes[i].lines[1].get_ydata()[np.where(np.round(axes[i].lines[1].get_xdata(),2) == np.around(mean,2))[0][0]]
    axes[i].plot([mean,mean], [ymin, yval], color="red", zorder=200) #need to set a high zorder to draw them in front of all the rest
```

![image](https://user-images.githubusercontent.com/4422950/52471470-433f8780-2b91-11e9-9643-2cd2b62fad5c.png)


Thanks again!

**Comment by leotac** [comment]
You're welcome!
