### ISSUE TITLE
Source files on PyPI

### ISSUE THREAD

**Issue by dirmeier** [sbebo/joypy#33]
Ciao Leonardo,
I was planning to submit your package to [conda-forge](https://github.com/conda-forge), such that it's installable using conda (since I want to put one of my packages there and yours is a dependency).

Would you mind to please put the source files of joypy on PyPI , too, i.e. submit the `tar.gz` next to the wheel? That would be great. Thanks!

Cheers,
Simon

**Comment by leotac** [comment]
Sure thing, just uploaded the source too. Thanks!

**Comment by dirmeier** [comment]
Cool, in the future ppl can download joypy using `conda install -c conda-forge joypy`
