### ISSUE TITLE
How to group/separate?

### ISSUE THREAD

**Issue by DeLaRiva** [sbebo/joypy#37]
I exactly would like to create a plot like [https://www.machinelearningplus.com/wp-content/uploads/2018/11/24_JoyPlot_joypy-min-1024x741.png](url)  found on https://www.machinelearningplus.com/plots/top-50-matplotlib-visualizations-the-master-plots-python/ , where they use `fig, axes = joypy.joyplot(mpg, column=['hwy', 'cty'], by="class", ylim='own', figsize=(14,10))`

To do so I use `fig, ax = joypy.joyplot(Temperatures_df, by="Transformer", figsize=(14,7),
                        linewidth=0.05,overlap=3,colormap=cm.OrRd_r)`
but I receive the following: 

![plot](https://user-images.githubusercontent.com/29283287/61430650-efe51880-a92a-11e9-8162-389130c778c4.JPG)

but I would like to have the variables separated and then each variable grouped by `"Transformer"`. Hence, I tried `fig, ax = joypy.joyplot(Temperatures_df, figsize=(14,7), linewidth=0.05,overlap=3, colormap=cm.OrRd_r)` but then I receive: 
![plot1](https://user-images.githubusercontent.com/29283287/61430740-3470b400-a92b-11e9-846b-b8a459954a38.JPG)

What I am actually looking for is a combination of both of them. Respectively I don't understand why I can't create the same appearance like in the first image as this fulfills my expectations already.
Why is that?

The `Temperatures_df` looks like following:

> BotTmp | EnvTmp | HPTmpClc | LTCTmp | Transformer
> timestamp
> 
> 2018-02-02 14:31:00 | NaN | NaN | 54.400000 | NaN | Transformer S1
> 2018-02-02 14:45:00 | NaN | NaN | 54.400000 | NaN | Transformer S1
> 2018-02-02 15:00:00 | NaN | NaN | 54.400000 | NaN | Transformer S1
> (...)
> 2018-10-25 01:30:00 | NaN | NaN | NaN | 30.790190 | Transformer S2

**Comment by leotac** [comment]
Hi, 

not sure what is your expected result. I would suggest looking at the notebook with examples, in the last few examples (about colors).
Currently, if you use both the `by` and `colormap `argument, the same colormap is applied to all groups. This is why you obtain the result in the first figure. (Not sure this is the most sensible default indeed, but it's like this at the moment).

You should use the `color `argument and pass explicitly the colors, if you want each group to have a separate color, like this:
```python
fig, axes = joypy.joyplot(iris,fill=True, legend=True, by="Name", color=["k","b","r","g"])
```
![exam](https://user-images.githubusercontent.com/1311290/64491424-be246a00-d268-11e9-9238-f97bd224bba0.png)

You could even pass a list of different colormaps, where the list has the same length as the number of groups. You can find both examples in the notebook.
