### ISSUE TITLE
pandas.plotting._tools not supported in pandas 0.25.0

### ISSUE THREAD

**Issue by simon-m-mudd** [sbebo/joypy#38]
I have not extensively tested this, but it seems the

`from pandas.plotting._tools import (_subplots, _flatten)`

does not work in the new pandas (0.25.0, released July 18th)

Error is: 
`    from pandas.plotting._tools import (_subplots, _flatten)`
`ModuleNotFoundError: No module named 'pandas.plotting._tools'`

The code works perfectly fine in pandas 0.24.2

**Comment by leotac** [comment]
It seems that starting from 0.25, pandas had moves those internal functions into
pandas.plotting._matplotlib.tools. 
You are welcome to open a PR with a fix - a quick one could be to use a try/except block around the current import and try the new one if the first one fails.

The real longer-term solution would be to stop relying on those 2 internal functions that are not guaranteed to be broken by newer releases of pandas.

**Comment by leotac** [comment]
Fixed by #39
