### ISSUE TITLE
Incorrect plotting of standard gaussian? 

### ISSUE THREAD

**Issue by diego898** [sbebo/joypy#54]
```
import numpy as np
from scipy.stats import norm
import joypy
joypy.joyplot([norm.pdf(np.linspace(-10,10))]);
```

produces: 

<img width="524" alt="image" src="https://user-images.githubusercontent.com/742407/98376020-89e14080-2008-11eb-817b-3121ce8ca7e8.png">

Why would there be a hump towards the right? Why would it be cut off towards the left?

**Comment by leotac** [comment]
Hi diego,

joypy will try to plot a density plot or a histogram of the data you provide.
If you want to plot passing a "density plot" or a histogram you already computed, you need to use the option `kind="values"` and take care of the xrange yourself.
See section **Plotting with pre-aggregated data** in the examples [here](https://github.com/sbebo/joypy/blob/master/Joyplot.ipynb)

In your case this does the trick:

```python
import numpy as np
from scipy.stats import norm
import joypy
joypy.joyplot([norm.pdf(np.linspace(-10,10))], kind="values", x_range=(0,50))
```

![image](https://user-images.githubusercontent.com/1311290/98788383-1ae95a80-2401-11eb-9abf-ca1af732c21e.png)
