### ISSUE TITLE
Update Iris Example in Readme

### ISSUE THREAD

**Issue by r0f1** [sbebo/joypy#56]
Hi, I propose this minimal working example for the Readme, as users will probably have sklearn already installed anyways:

```python
import joypy
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True).data
fig, axes = joypy.joyplot(iris)
```

**Comment by leotac** [comment]
Hi Florian,

That makes complete sense. I'll update the example.

Il mar 30 mar 2021, 17:04 Florian Rohrer ***@***.***> ha
scritto:
