### ISSUE TITLE
"By" Column Is Not Properly Removed

### ISSUE THREAD

**Issue by r0f1** [sbebo/joypy#57]
I created a column `key` to print different groups of my dataset. However, the key is still present in the histograms (orange bars).

```python
import joypy
from sklearn.datasets import load_iris

df = load_iris(as_frame=True).data
df["key"] = df.index % 3
df = df[["sepal length (cm)", "key"]]
_ = joypy.joyplot(df, by="key", hist=True)
```

![image](https://user-images.githubusercontent.com/7324891/113291305-20353c00-92f3-11eb-8d0f-0be48708c718.png)

**Comment by leotac** [comment]
Indeed it looks like a bug. Let me fix it.
