### ISSUE TITLE
Github Tags/Releases?

### ISSUE THREAD

**Issue by nileshpatra** [sbebo/joypy#65]
Hi,

The latest tag on github [here](https://github.com/leotac/joypy/tags) is still 0.2.2 whilst the version has progressed to 0.2.5.
Actually, I maintain this package in debian, and we take the source package from github (not pypi for several reasons) and hence it'd
be very helpful if you could propagate the missing tag(s) (at least the latest one)

Could you please push the relevant tag?

=============================================================================================

CC: @leotac

**Comment by leotac** [comment]
Oh, you're right. Must have forgotten to push the tags. Let me do that.
And then I probably need to integrate the release process in a github action.

**Comment by nileshpatra** [comment]
Thanks got doing that, but something is odd, you tagged a 0.2.6 release, but the release version in `joypy/__init__.py` is still `0.2.5`

https://github.com/leotac/joypy/blob/5c713342d1e21bed0bb33825257cab3dfb950fe4/joypy/__init__.py#L3

Can you bump that and re-tag please?
