### ISSUE TITLE
Different issue on import for 0.1.4

### ISSUE THREAD

**Issue by WMGoBuffs** [sbebo/joypy#7]
I saw the other import error in the solved issues, but this one is different. I'm using Pandas 0.20.3 

File "myscript.py", line 17, in \<module\>
import joypy
  File "/home/user/anaconda2/lib/python2.7/site-packages/joypy/__init__.py", line 1, in <module>
    from .joyplot import joyplot, plot_density, _joyplot
  File "/home/user/anaconda2/lib/python2.7/site-packages/joypy/joyplot.py", line 221
    raise ValueError("At least a column/group haNo numeric values found. Joyplot requires at least a numeric column/group.")

**Comment by leotac** [comment]
Oops, I checked in some code that I shouldn't have when setting the new version number.

**Comment by WMGoBuffs** [comment]
that's ok, thanks for the cool package! I installed via PIP, so do you know how long any changes might take to propagate there?

**Comment by leotac** [comment]
I don't know exactly, but I just checked and I got the latest version (0.1.5).

**Comment by WMGoBuffs** [comment]
Thanks, it works for me now!  Just a note, you may want to add the `future` package to your dependency list.
