### ISSUE TITLE
Calling `xlim` has unexpected effect

### ISSUE THREAD

**Issue by jbloom** [sbebo/joypy#9]
If you create a joyplot, and then subsequently set the xlimits by calling `matplotlib.pyplot.xlim(xmin, xmax)`, the x-axis labels shift but the data does not shift to reflect the new x range.

This can easily lead to incorrectly plotted data because no warning is given -- the axis labels just stop reflecting the actual data.

For instance, below is the **exact same** data plotted with joyplot, but in the first case there was a subsequent call to `xlim` to set a narrower xrange and in the second case there was not. As you can see, the xticks shifted but not the data.

I'm guessing the preferred way to set the xlimits is instead via the *xrange* parameter of `joyplot`, but I still worry the behavior described in this issue could easily lead to incorrect plots.

![screen shot 2017-11-24 at 8 15 40 am](https://user-images.githubusercontent.com/1906801/33218062-b725dcc4-d0ef-11e7-8083-4a6956b5adff.png)

**Comment by leotac** [comment]
You're right. The thing is, in my implementation, each one of the density subplots has its own axes, with their own xlim and ylim. Then there's an *outer* axis pair, behind all the other ones, that is used e.g. for xticks and xlabels. The xlim values of all the subplots are the same by construction, but there is no hard constraint that makes them so. 
With `matplotlib.pyplot.xlim(xmin, xmax)` you're changing the lims of the[ current X axis ](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.xlim.html?highlight=matplotlib%20pyplot%20xlim#matplotlib-pyplot-xlim)-- whatever current means in this case. I guess it is the last one, i.e., the "container" axis, so you're not changing the xlims of the single subplots. To get that effect, you should loop over all the axes returned by joyplot (in your case, the first 4 are your density subplots, + the last one is the "container" one) and set the xlim of each of them.

**Comment by jbloom** [comment]
OK, thanks.

**Comment by TobiasWegener** [comment]
Hallo, this is very nice tool and I would like to use it in my Phd thesis.
However, I have some issue to set the xlabel. I see in the example above, this seems possible?
Can you tell me how to do it the standard method I use with seaborn an matplotlib and pylab in the jupyter notebook is:
 `xlabel('label of x')`
or similar.
but this gives back: 
 ```
<ipython-input-316-4a720c777783> in <module>()
 5 xlabel('some x labe')
 TypeError: 'str' object is not callable
```
If I remove the xlabel, the plot works perfectly fine and looks like this.

[05_all_grainsize_distribution_Joyplot.pdf](https://github.com/sbebo/joypy/files/1507409/05_all_grainsize_distribution_Joyplot.pdf)

Thank you in advance, for this tool and all the best,
Tobias

ps. `plt.xlabel('label of x')` doesn't work either.

**Comment by leotac** [comment]
Hi Tobias, you should apply `set_xlabel` to the last axes returned by the function. Something like this:

``` python
fig, axes = joypy.joyplot(data)
axes[-1].set_xlabel("My x label")
```
![xlabel](https://user-images.githubusercontent.com/1311290/33318183-0e37c692-d43a-11e7-9d15-0c759baf0c45.png)

**Comment by TobiasWegener** [comment]
Hallo sbebo,
Ah, now I see, my fault.

Thank you very much for the fast help and the great work!
Best regards,

Tobias
